---
title: "Field_test_eval"
author: "Peter Paziczki"
date: "September 19, 2018"
output: html_document
---

<style>
body {
text-align: justify}
</style>

```{r setup, include=FALSE}
rm(list=ls())
knitr::opts_chunk$set(echo = TRUE, warning = FALSE, echo = FALSE)
```

```{r echo=FALSE}
# Loading necessary libraries
library(ggplot2)
library(data.table)

# Loading the data
data_source <- fread(file = "field_test_db_2018_6_1-2018_9_19.csv" , stringsAsFactors = F )
# Making a copy so the source cannot ne modified
my_data <- data_source
# Uninteded disengagements only
unintended_disengs <- my_data[Intended == 'FALSE']
```

```{r}
# Some general statistics
#plot(density(my_data$Distance)) # calling a density function on bmi

# All values in all columns
for (column_name in colnames(my_data)){
  print(my_data[,.N, by = column_name])
}
```

```{r}
# Having all the self driving sessions after the xth uninteded disengagements globally
x = 50
data <- my_data[Start >= my_data[Intended == 'FALSE', Start][x]]
data[Intended == 'FALSE',.N]
y <- nrow(data)

# Global stats
stats <- data[,list(sum_kms_driven = sum(Distance), self_driving_sessions = nrow(data))]
stats[, avg_kms_driven_per_u_disengs := sum_kms_driven/self_driving_sessions]
stats

# Breaking it down to local stats
stats <- data[,list(self_driving_sessions = .N, sum_kms_driven = sum(Distance)), by = Location]
stats[, avg_kms_driven_per_u_disengs := sum_kms_driven/self_driving_sessions]
stats

# Having all the self driving sessions after the xth uninteded disengagements locally
x = 50

for (country in unique(my_data$Location)){
  data <- my_data[Location == country]
  data <- data[Start >= data[Intended == 'FALSE', Start][x]]
  # Selfcheck
  data[Intended == 'FALSE',.N]
  stats <- data[,list(Location = country, self_driving_sessions = .N, sum_kms_driven = sum(Distance))]
  stats[, avg_kms_driven_per_u_disengs := sum_kms_driven/self_driving_sessions]
  print(stats)
}

```

```{r}
my_data[,.N, by = list(`Disengagement category`, Location)]
#table(data$`Disengagement category`)
my_data[Location == 'Hungary', .N, by = list(`Disengagement category`, Location)]
ggplot(my_data, aes(`Disengagement category`)) + geom_bar() + facet_wrap(~Location)
ggplot(my_data, aes(`Disengagement category`)) + geom_bar() + facet_wrap(~`aiDrive version`)
```

```{r}
# Filtering
Sys.time()
Sys.Date()
basis_date <- Sys.Date()
#data <- data[Start > ]
```